/* Generated By:JavaCC: Do not edit this line. LibParserTokenManager.java */
package lib;

/** Token Manager. */
public class LibParserTokenManager implements LibParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x2004000000L) != 0L)
         {
            jjmatchedKind = 51;
            return 7;
         }
         if ((active0 & 0x110100000L) != 0L)
         {
            jjmatchedKind = 51;
            return 153;
         }
         if ((active0 & 0x8000L) != 0L)
            return 10;
         if ((active0 & 0x40000L) != 0L)
         {
            jjmatchedKind = 51;
            return 122;
         }
         if ((active0 & 0x1000L) != 0L)
            return 18;
         if ((active0 & 0x40e9ca0000L) != 0L)
         {
            jjmatchedKind = 51;
            return 54;
         }
         if ((active0 & 0x1200000000L) != 0L)
         {
            jjmatchedKind = 51;
            return 71;
         }
         if ((active0 & 0x2200000L) != 0L)
         {
            jjmatchedKind = 51;
            return 132;
         }
         return -1;
      case 1:
         if ((active0 & 0x7000000000L) != 0L)
            return 54;
         if ((active0 & 0x3fffe0000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 1;
            return 54;
         }
         return -1;
      case 2:
         if ((active0 & 0x3ffbe0000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 2;
            return 54;
         }
         if ((active0 & 0x400000L) != 0L)
            return 54;
         return -1;
      case 3:
         if ((active0 & 0x30fbe0000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 51;
               jjmatchedPos = 3;
            }
            return 54;
         }
         if ((active0 & 0xf0000000L) != 0L)
            return 54;
         return -1;
      case 4:
         if ((active0 & 0x2451e0000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 4;
            return 54;
         }
         if ((active0 & 0x10aa00000L) != 0L)
            return 54;
         return -1;
      case 5:
         if ((active0 & 0x441e0000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 5;
            return 54;
         }
         if ((active0 & 0x201000000L) != 0L)
            return 54;
         return -1;
      case 6:
         if ((active0 & 0x44180000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 6;
            return 54;
         }
         if ((active0 & 0x60000L) != 0L)
            return 54;
         return -1;
      case 7:
         if ((active0 & 0x40100000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 7;
            return 54;
         }
         if ((active0 & 0x4080000L) != 0L)
            return 54;
         return -1;
      case 8:
         if ((active0 & 0x40100000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 8;
            return 54;
         }
         return -1;
      case 9:
         if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 9;
            return 54;
         }
         if ((active0 & 0x100000L) != 0L)
            return 54;
         return -1;
      case 10:
         if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 10;
            return 54;
         }
         return -1;
      case 11:
         if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 11;
            return 54;
         }
         return -1;
      case 12:
         if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 12;
            return 54;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 34:
         return jjStartNfaWithStates_0(0, 12, 18);
      case 36:
         return jjStartNfaWithStates_0(0, 15, 10);
      case 40:
         return jjStopAtPos(0, 5);
      case 41:
         return jjStopAtPos(0, 6);
      case 44:
         return jjStopAtPos(0, 7);
      case 45:
         return jjStopAtPos(0, 14);
      case 46:
         return jjStopAtPos(0, 16);
      case 58:
         return jjStopAtPos(0, 8);
      case 59:
         return jjStopAtPos(0, 11);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x1200000000L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0xc0080000L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x1000000L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x8400000L);
      case 72:
         return jjMoveStringLiteralDfa1_0(0x800000L);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x20000L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x2004000000L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x2200000L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x110100000L);
      case 87:
         return jjMoveStringLiteralDfa1_0(0x40000L);
      case 95:
         return jjStopAtPos(0, 13);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x4000000000L);
      case 123:
         return jjStopAtPos(0, 9);
      case 125:
         return jjStopAtPos(0, 10);
      default :
         return jjMoveNfa_0(8, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0x100120000L);
      case 76:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000L);
      case 77:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 36, 54);
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 37, 54);
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0xc4800000L);
      case 84:
         return jjMoveStringLiteralDfa2_0(active0, 0x2200000L);
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x200080000L);
      case 89:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000L);
      case 111:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 38, 54);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0xa200000L);
      case 66:
         return jjMoveStringLiteralDfa3_0(active0, 0x60000L);
      case 68:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(2, 22, 54);
         break;
      case 73:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
      case 77:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0xc1000000L);
      case 80:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L);
      case 83:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      case 84:
         return jjMoveStringLiteralDfa3_0(active0, 0x320000000L);
      case 85:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(3, 28, 54);
         else if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(3, 29, 54);
         return jjMoveStringLiteralDfa4_0(active0, 0x100000L);
      case 70:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000L);
      case 72:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0xc000000L);
      case 75:
         if ((active0 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000L);
      case 76:
         return jjMoveStringLiteralDfa4_0(active0, 0x100080000L);
      case 82:
         return jjMoveStringLiteralDfa4_0(active0, 0xa20000L);
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x1040000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000L);
      case 67:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000L);
      case 68:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000L);
      case 69:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(4, 32, 54);
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000L);
      case 70:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(4, 25, 54);
         break;
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000L);
      case 76:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 27, 54);
         break;
      case 79:
         return jjMoveStringLiteralDfa5_0(active0, 0x200100000L);
      case 83:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(4, 23, 54);
         break;
      case 84:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(4, 21, 54);
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 68:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(5, 24, 54);
         break;
      case 70:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000L);
      case 73:
         return jjMoveStringLiteralDfa6_0(active0, 0x4080000L);
      case 79:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000L);
      case 82:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(5, 33, 54);
         return jjMoveStringLiteralDfa6_0(active0, 0x20000L);
      case 84:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(6, 18, 54);
         break;
      case 76:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000000L);
      case 78:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000L);
      case 79:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000L);
      case 89:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(6, 17, 54);
         return jjMoveStringLiteralDfa7_0(active0, 0x100000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000L);
      case 71:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(7, 19, 54);
         break;
      case 76:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000L);
      case 78:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(7, 26, 54);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa9_0(active0, 0x100000L);
      case 69:
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa10_0(active0, 0x40000000L);
      case 82:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(9, 20, 54);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 84:
         return jjMoveStringLiteralDfa11_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa12_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 79:
         return jjMoveStringLiteralDfa13_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 78:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(13, 30, 54);
         break;
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 167;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 8:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 39)
                        kind = 39;
                     jjAddStates(0, 3);
                  }
                  else if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 18;
                  else if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 4:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 9:
                  if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(4, 7);
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(11, 12);
                  break;
               case 12:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) != 0L && kind > 42)
                     kind = 42;
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(15, 16);
                  break;
               case 16:
                  if (curChar == 46 && kind > 42)
                     kind = 42;
                  break;
               case 17:
                  if (curChar == 34)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 19:
                  if (curChar == 47)
                     jjCheckNAddTwoStates(20, 21);
                  break;
               case 20:
                  if ((0xe00000000000L & l) != 0L)
                     jjCheckNAddTwoStates(20, 21);
                  break;
               case 21:
                  if (curChar == 34 && kind > 45)
                     kind = 45;
                  break;
               case 22:
               case 27:
                  if (curChar == 47)
                     jjCheckNAdd(19);
                  break;
               case 23:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 28:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 77:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 39)
                     kind = 39;
                  jjAddStates(0, 3);
                  break;
               case 78:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 79:
                  if ((0x3ff000000000000L & l) != 0L && kind > 35)
                     kind = 35;
                  break;
               case 80:
                  if ((0x3ff000000000000L & l) != 0L && kind > 39)
                     kind = 39;
                  break;
               case 81:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 82:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 83:
                  if ((0x3ff000000000000L & l) != 0L && kind > 40)
                     kind = 40;
                  break;
               case 84:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 85:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 86:
                  if ((0x3ff000000000000L & l) != 0L && kind > 49)
                     kind = 49;
                  break;
               case 91:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 7:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 51)
                        kind = 51;
                     jjCheckNAdd(54);
                  }
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 51)
                        kind = 51;
                     jjCheckNAdd(54);
                  }
                  if (curChar == 84)
                     jjAddStates(8, 11);
                  else if (curChar == 83)
                     jjAddStates(12, 16);
                  else if (curChar == 87)
                     jjAddStates(17, 18);
                  else if (curChar == 77)
                     jjAddStates(19, 22);
                  else if (curChar == 70)
                     jjAddStates(23, 26);
                  else if (curChar == 65)
                     jjAddStates(27, 28);
                  else if (curChar == 74)
                     jjAddStates(29, 31);
                  else if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 52;
                  else if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 45;
                  else if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 38;
                  else if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 132:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 51)
                        kind = 51;
                     jjCheckNAdd(54);
                  }
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 149;
                  else if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 142;
                  else if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 138;
                  if (curChar == 117)
                     jjCheckNAdd(109);
                  else if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 71:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 51)
                        kind = 51;
                     jjCheckNAdd(54);
                  }
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 75;
                  else if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 122:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 51)
                        kind = 51;
                     jjCheckNAdd(54);
                  }
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 128;
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 153:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 51)
                        kind = 51;
                     jjCheckNAdd(54);
                  }
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 165;
                  else if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 159;
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 154;
                  else if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 0:
                  if (curChar == 101 && kind > 41)
                     kind = 41;
                  break;
               case 1:
               case 88:
                  if (curChar == 109)
                     jjCheckNAdd(0);
                  break;
               case 2:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 5:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 18:
                  if (curChar == 104)
                     jjAddStates(32, 33);
                  break;
               case 20:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjAddStates(34, 35);
                  break;
               case 24:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 29:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 30:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if (curChar == 114 && kind > 48)
                     kind = 48;
                  break;
               case 34:
               case 40:
               case 47:
               case 144:
                  if (curChar == 101)
                     jjCheckNAdd(33);
                  break;
               case 35:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 36:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 41:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 42:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 43:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 44:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 45:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 48:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 49:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 50:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 51:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 52:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 53:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 54:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAdd(54);
                  break;
               case 55:
                  if (curChar == 74)
                     jjAddStates(29, 31);
                  break;
               case 56:
                  if (curChar == 121 && kind > 48)
                     kind = 48;
                  break;
               case 57:
               case 102:
                  if (curChar == 114)
                     jjCheckNAdd(56);
                  break;
               case 58:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 59:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 60:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 61:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
                  if (curChar == 101 && kind > 48)
                     kind = 48;
                  break;
               case 63:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 64:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 65:
                  if (curChar == 108)
                     jjCheckNAdd(56);
                  break;
               case 66:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 67:
                  if (curChar == 65)
                     jjAddStates(27, 28);
                  break;
               case 68:
                  if (curChar == 108 && kind > 48)
                     kind = 48;
                  break;
               case 69:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 72:
                  if (curChar == 116 && kind > 48)
                     kind = 48;
                  break;
               case 73:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 74:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 75:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 76:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 87:
                  if (curChar == 70)
                     jjAddStates(23, 26);
                  break;
               case 89:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 90:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 92:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 94:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 95:
                  if (curChar == 105 && kind > 46)
                     kind = 46;
                  break;
               case 96:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 97:
                  if (curChar == 121 && kind > 47)
                     kind = 47;
                  break;
               case 98:
               case 111:
               case 123:
               case 134:
               case 140:
               case 156:
               case 161:
                  if (curChar == 97)
                     jjCheckNAdd(97);
                  break;
               case 99:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 103:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 104:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 105:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 108:
                  if (curChar == 77)
                     jjAddStates(19, 22);
                  break;
               case 109:
                  if (curChar == 110 && kind > 46)
                     kind = 46;
                  break;
               case 110:
                  if (curChar == 111)
                     jjCheckNAdd(109);
                  break;
               case 112:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 113:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 114:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 115:
                  if (curChar == 104 && kind > 48)
                     kind = 48;
                  break;
               case 116:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 117:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 118:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if (curChar == 97)
                     jjCheckNAdd(56);
                  break;
               case 120:
                  if (curChar == 87)
                     jjAddStates(17, 18);
                  break;
               case 121:
                  if (curChar == 100 && kind > 46)
                     kind = 46;
                  break;
               case 124:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 125:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 126:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 127:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 130:
                  if (curChar == 83)
                     jjAddStates(12, 16);
                  break;
               case 131:
                  if (curChar == 116 && kind > 46)
                     kind = 46;
                  break;
               case 133:
                  if (curChar == 117)
                     jjCheckNAdd(109);
                  break;
               case 135:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 136:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 137:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 139:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 141:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 142:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 143:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 145:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 146:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 147:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 146;
                  break;
               case 148:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 149:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 150:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 151:
                  if (curChar == 84)
                     jjAddStates(8, 11);
                  break;
               case 152:
                  if (curChar == 101 && kind > 46)
                     kind = 46;
                  break;
               case 154:
                  if (curChar == 117 && kind > 46)
                     kind = 46;
                  break;
               case 155:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 157:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 156;
                  break;
               case 158:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 159:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 160:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 159;
                  break;
               case 162:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 163:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 164:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 165:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 166:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 167 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   78, 80, 81, 84, 11, 12, 15, 16, 153, 155, 160, 166, 132, 133, 139, 143, 
   150, 122, 129, 110, 114, 118, 119, 94, 96, 101, 107, 71, 76, 61, 64, 66, 
   26, 32, 20, 21, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\50", "\51", "\54", "\72", "\173", "\175", "\73", 
"\42", "\137", "\55", "\44", "\56", "\114\111\102\122\101\122\131", 
"\127\105\102\123\111\124\105", "\102\125\111\114\104\111\116\107", 
"\124\111\115\105\117\106\131\105\101\122", "\123\124\101\122\124", "\105\116\104", "\110\117\125\122\123", 
"\103\114\117\123\105\104", "\123\124\101\106\106", "\120\117\123\111\124\111\117\116", 
"\105\115\101\111\114", "\124\131\120\105", "\122\101\124\105", 
"\102\117\117\113\103\117\114\114\105\103\124\111\117\116", "\102\117\117\113", "\124\111\124\114\105", "\101\125\124\110\117\122", null, 
null, "\101\115", "\120\115", "\164\157", null, null, null, null, null, null, null, 
null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xbe7fbffffffe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[167];
private final int[] jjstateSet = new int[334];
protected char curChar;
/** Constructor. */
public LibParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public LibParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 167; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
