/* Generated By:JavaCC: Do not edit this line. LibParserConstants.java */
package lib;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LibParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LP = 5;
  /** RegularExpression Id. */
  int RP = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int COLON = 8;
  /** RegularExpression Id. */
  int LB = 9;
  /** RegularExpression Id. */
  int RB = 10;
  /** RegularExpression Id. */
  int SEMI = 11;
  /** RegularExpression Id. */
  int QUOTE = 12;
  /** RegularExpression Id. */
  int UNDERSCORE = 13;
  /** RegularExpression Id. */
  int HYPHEN = 14;
  /** RegularExpression Id. */
  int LIBRARY = 15;
  /** RegularExpression Id. */
  int WEBSITE = 16;
  /** RegularExpression Id. */
  int BUILDING = 17;
  /** RegularExpression Id. */
  int TIMEOFYEAR = 18;
  /** RegularExpression Id. */
  int START = 19;
  /** RegularExpression Id. */
  int END = 20;
  /** RegularExpression Id. */
  int HOURS = 21;
  /** RegularExpression Id. */
  int CLOSED = 22;
  /** RegularExpression Id. */
  int STAFF = 23;
  /** RegularExpression Id. */
  int POSITION = 24;
  /** RegularExpression Id. */
  int EMAIL = 25;
  /** RegularExpression Id. */
  int TYPE = 26;
  /** RegularExpression Id. */
  int RATE = 27;
  /** RegularExpression Id. */
  int BOOKCOLLECTION = 28;
  /** RegularExpression Id. */
  int BOOK = 29;
  /** RegularExpression Id. */
  int TITLE = 30;
  /** RegularExpression Id. */
  int AUTHOR = 31;
  /** RegularExpression Id. */
  int DIGIT = 32;
  /** RegularExpression Id. */
  int BUILDING_NUMBER = 33;
  /** RegularExpression Id. */
  int AM = 34;
  /** RegularExpression Id. */
  int PM = 35;
  /** RegularExpression Id. */
  int TO = 36;
  /** RegularExpression Id. */
  int DAY = 37;
  /** RegularExpression Id. */
  int YEAR = 38;
  /** RegularExpression Id. */
  int PROTOCOL1 = 39;
  /** RegularExpression Id. */
  int PROTOCOL2 = 40;
  /** RegularExpression Id. */
  int URL = 41;
  /** RegularExpression Id. */
  int DAYS_SHORT = 42;
  /** RegularExpression Id. */
  int DAYS_LONG = 43;
  /** RegularExpression Id. */
  int MONTH = 44;
  /** RegularExpression Id. */
  int TIME = 45;
  /** RegularExpression Id. */
  int LETTER = 46;
  /** RegularExpression Id. */
  int WORD = 47;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"\\\"\"",
    "\"_\"",
    "\"-\"",
    "\"LIBRARY\"",
    "\"WEBSITE\"",
    "\"BUILDING\"",
    "\"TIMEOFYEAR\"",
    "\"START\"",
    "\"END\"",
    "\"HOURS\"",
    "\"CLOSED\"",
    "\"STAFF\"",
    "\"POSITION\"",
    "\"EMAIL\"",
    "\"TYPE\"",
    "\"RATE\"",
    "\"BOOKCOLLECTION\"",
    "\"BOOK\"",
    "\"TITLE\"",
    "\"AUTHOR\"",
    "<DIGIT>",
    "<BUILDING_NUMBER>",
    "\"AM\"",
    "\"PM\"",
    "\"to\"",
    "<DAY>",
    "<YEAR>",
    "\"http://\"",
    "\"https://\"",
    "<URL>",
    "<DAYS_SHORT>",
    "<DAYS_LONG>",
    "<MONTH>",
    "<TIME>",
    "<LETTER>",
    "<WORD>",
  };

}
