/* Generated By:JavaCC: Do not edit this line. LibParserConstants.java */
package lib;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LibParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LP = 5;
  /** RegularExpression Id. */
  int RP = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int LB = 8;
  /** RegularExpression Id. */
  int RB = 9;
  /** RegularExpression Id. */
  int SEMI = 10;
  /** RegularExpression Id. */
  int LIBRARY = 11;
  /** RegularExpression Id. */
  int WEBSITE = 12;
  /** RegularExpression Id. */
  int BUILDING = 13;
  /** RegularExpression Id. */
  int TIMEOFYEAR = 14;
  /** RegularExpression Id. */
  int START = 15;
  /** RegularExpression Id. */
  int END = 16;
  /** RegularExpression Id. */
  int HOURS = 17;
  /** RegularExpression Id. */
  int CLOSED = 18;
  /** RegularExpression Id. */
  int STAFF = 19;
  /** RegularExpression Id. */
  int POSITION = 20;
  /** RegularExpression Id. */
  int EMAIL = 21;
  /** RegularExpression Id. */
  int TYPE = 22;
  /** RegularExpression Id. */
  int RATE = 23;
  /** RegularExpression Id. */
  int BOOKCOLLECTION = 24;
  /** RegularExpression Id. */
  int BOOK = 25;
  /** RegularExpression Id. */
  int TITLE = 26;
  /** RegularExpression Id. */
  int AUTHOR = 27;
  /** RegularExpression Id. */
  int DIGIT = 28;
  /** RegularExpression Id. */
  int BUILDING_NUMBER = 29;
  /** RegularExpression Id. */
  int AM = 30;
  /** RegularExpression Id. */
  int PM = 31;
  /** RegularExpression Id. */
  int DAY = 32;
  /** RegularExpression Id. */
  int HTTP = 33;
  /** RegularExpression Id. */
  int HTTPS = 34;
  /** RegularExpression Id. */
  int DAYS_SHORT = 35;
  /** RegularExpression Id. */
  int DAYS_LONG = 36;
  /** RegularExpression Id. */
  int LETTER = 37;
  /** RegularExpression Id. */
  int WORD = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"Library\"",
    "\"WEBSITE\"",
    "\"BUILDING\"",
    "\"TIMEOFYEAR\"",
    "\"START\"",
    "\"END\"",
    "\"HOURS\"",
    "\"CLOSED\"",
    "\"STAFF\"",
    "\"POSITION\"",
    "\"EMAIL\"",
    "\"TYPE\"",
    "\"RATE\"",
    "\"BOOKCOLLECTION\"",
    "\"BOOK\"",
    "\"TITLE\"",
    "\"AUTHOR\"",
    "<DIGIT>",
    "<BUILDING_NUMBER>",
    "\"AM\"",
    "\"PM\"",
    "<DAY>",
    "\"http://\"",
    "\"https://\"",
    "<DAYS_SHORT>",
    "<DAYS_LONG>",
    "<LETTER>",
    "<WORD>",
  };

}
