/* Generated By:JavaCC: Do not edit this line. LibParserConstants.java */
package lib;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LibParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LIBRARY = 5;
  /** RegularExpression Id. */
  int WEBSITE = 6;
  /** RegularExpression Id. */
  int BUILDING = 7;
  /** RegularExpression Id. */
  int TIMEOFYEAR = 8;
  /** RegularExpression Id. */
  int START = 9;
  /** RegularExpression Id. */
  int END = 10;
  /** RegularExpression Id. */
  int HOURS = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Library\"",
    "\"WEBSITE\"",
    "\"BUILDING\"",
    "\"TIMEOFYEAR\"",
    "\"START\"",
    "\"END\"",
    "\"HOURS\"",
    "\"asdads\"",
  };

}
